# Generated by Django 4.0.7 on 2023-08-15 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('is_private', models.IntegerField()),
                ('title', models.TextField(null=True)),
                ('preface', models.TextField(null=True)),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=10)),
                ('sequence', models.CharField(max_length=10)),
                ('item', models.TextField()),
            ],
            options={
                'db_table': 'pages',
                'managed': False,
            },
        ),
    ]
