# Generated by Django 4.0.7 on 2023-10-27 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountconnection',
            fields=[
                ('secret_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='secret_user_connections', serialize=False, to='users.users')),
                ('pw', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'accountconnection',
                'managed': False,
            },
        ),
    ]
