# Generated by Django 4.0.7 on 2023-12-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretmode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersecretpostmatches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_confirmed', models.IntegerField()),
                ('connection_date', models.DateTimeField()),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usersecretpostmatches',
                'managed': False,
            },
        ),
    ]
