# Generated by Django 4.0.7 on 2023-10-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatparticipant',
            options={'managed': True},
        ),
    ]
