# Generated by Django 4.0.7 on 2023-10-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0002_alter_chatparticipant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatparticipant',
            options={'managed': False},
        ),
    ]
